### PR TITLE
feature(domain) - Added cname file for cloudflare

### PR DESCRIPTION
**Pull request by aceew**
Adding a CNAME file to link cloudflare up the site.

### CODE REVIEW

**Review by SecondeJK — COMMENTED** [review]
Yep, merge it!

**Comment by alexwilson** [comment]
Hold on, who owns the Cloudflare property?

**Comment by aceew** [comment]
Hey, I created the account under Jim's email, but right now I'm the only one with access. We should probably set something up that we can all access easily.

**Comment by alexwilson** [comment]
Aite. I have an account with pro and apparently subaccounts we can transfer
to, but subaccounts are a bit tricky -- will raise a ticket with support to
see if they can help.

Should suggest that Fastly offer a free CDN tier to open source projects
too!

**Pull request merged**
